spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curioushub
    username: root
    password: # Add your MySQL password here
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: false
      pool-name: CuriousHubHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Fixes the issue with pattern matching

  servlet:
    multipart:
      max-file-size: 10MB  # Set the maximum size for uploaded files
      max-request-size: 10MB  # Set the maximum request size, including files

server:
  port: 8080
  servlet:
    context-path: /curioushub  # Defines your context path

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

file:
  upload-dir: C:/Users/aidal/Desktop/CuriousHub/CuriousHub/src/main/resources/uploads


